### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by SiddheshM13** [ankitbvs/Automated-ETL-pipeline-to-Analyze-US-Security-Financial-Documents#1]
How did you bypass the HTTP error that occurs while reading data from the urls?

**Comment by Joheon** [comment]
yea, how?

**Comment by SiddheshM13** [comment]
So, I managed to bypass this issue using a try-except statement. The while loop will iterate using a variable and whenever the exception occurs, the exception handling restarts the loop using the same value of the variable it was stopped on. Worked fine.

**Comment by Joheon** [comment]
can you please send the code when I tried to implement it, got an error as("decoding str is not supported")
